# Generated by Django 3.0.2 on 2020-02-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSCapabilitySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='View Only', max_length=100, unique=True)),
                ('load_profile', models.BooleanField(default=False)),
                ('outage_mgmt', models.BooleanField(default=False)),
                ('editing', models.BooleanField(default=False)),
                ('power_flow', models.BooleanField(default=False)),
                ('model_editing', models.BooleanField(default=False)),
                ('batch_delete_selection', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GSInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='EPE', max_length=100, unique=True)),
                ('gis_server', models.CharField(default='', max_length=100)),
                ('db_server', models.CharField(default='', max_length=100)),
                ('db_instance', models.CharField(default='', max_length=100)),
                ('map_instance', models.CharField(default='', max_length=100)),
                ('sde_instance', models.CharField(default='', max_length=100)),
                ('sde_pfx', models.CharField(default='', max_length=100)),
                ('grid_instance', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
