# Generated by Django 3.0.2 on 2020-02-04 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('eneri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capabilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eneri.GSCapabilitySet')),
                ('default_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_instance', to='eneri.GSInstance')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('instances', models.ManyToManyField(related_name='instances', to='eneri.GSInstance')),
            ],
        ),
    ]
